#!/bin/sh 

export EDITOR="nvim"
export TERMINAL="alacritty"
export BROWSER="firefox"
export MAINSCREEN="LVDS-1"
export SECSCREEN="VGA-1"

export PATH="$PATH:$HOME/.local/bin"
export PATH="$PATH:$HOME/.dotfiles/bin"

[[ -f ~/.bashrc ]] && . ~/.bashrc

[[ -z $DISPLAY ]] && startx "$HOME/.config/X11/xinitrc"
