
# Makes seahorse work, related to keyring? no clue...
# Some pcs need it, some don't
dbus-update-activation-environment --systemd DISPLAY

# Set keyboard language
setxkbmap -layout us,gr -option grp:alt_shift_toggle

# Map Caps lock to ESC 
setxkbmap -option caps:escape

xbindkeys -f "$HOME/.config/xbindkeys/config"

eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

owncloud &

exec i3
