#!/bin/bash


tpid=11

# Step 2: Find out if touchpad is enabled or not
status=`xinput list-props ${tpid} | grep Device\ Enabled | sed -e 's/.*\:[ \t]\+//g'`

# Step 3 enable/disable touchpad accordingly
if [ 0 -eq ${status} ] ; then
    xinput enable ${tpid}
else
    xinput disable ${tpid}
fi
