#!/bin/sh


selection=$( printf "(e) Extend Screen\n(m) Main Screen\n(s) Secondary Screen" | dmenu -l 3 )

case "$selection" in
	\(e*) ~/.dotfiles/scripts/screen-extend;;
	\(m*) ~/.dotfiles/scripts/screen-main;;
	\(s*) ~/.dotfiles/scripts/screen-secondary;;
esac
