#!/bin/sh


DOTFILES="$HOME/.dotfiles"
CONFIGS="alacritty emacs git i3 i3blocks ideavimrc profile screenrc tmux vim xbindkeys xinitrc Xresources"

source "$DOTFILES/bin/colors"

printf "%-10s\t%s\t%s\t%s\n" "" EXISTS SYMLINK SAME
for x in $CONFIGS; do 
	LOCAL=$( $DOTFILES/setup/getlocal $x )

	EXISTS=yes
	[ -f $LOCAL ] || EXISTS="${FG_RED}no$NC"

	SYMLINK="${FG_RED}yes$NC"
	[ -L $LOCAL ] || SYMLINK=no

	SAME=yes
	diff "$LOCAL" "$DOTFILES/config/$x" &>/dev/null || SAME="${FG_RED}no$NC"

	printf "%-10s\t%s\t%s\t%s\n" $x $EXISTS $SYMLINK $SAME
done


