#!/bin/bash

## Include this file in bashrc

# Get branch prompt
source ~/.dotfiles/bash/aliases
source ~/.dotfiles/bash/functions
source ~/.dotfiles/bash/git-prompt.sh

GIT_PS1_SHOWCOLORHINTS=1
GIT_PS1_SHOWDIRTYSTATE=1
GIT_PS1_SHOWSTASHSTATE=1
GIT_PS1_SHOWUNTRACKEDFILES=1
export PS1="${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00;33m\]\$(__git_ps1)\[\033[01;34m\] \n\$ \[\033[00m\]"

# Add custom bin folder
# SHOULD BE CALLED IN .profile
#export PATH="$PATH:$HOME/.dotfiles/bin"

# Don't show full path
export PROMPT_DIRTRIM=3

# Remap Caps Lock to ESC
# SHOULD BE CALLED IN .xinitrc
#setxkbmap -option caps:escape
# Add this for permanence
#XKBOPTIONS="caps:escape"

# Handle /dev autocompletion
dev_list=$( ls ~/.dotfiles/dev )
complete -W "$dev_list" 'dev'

# Composer autocompletion
complete -F _composer_scripts composer

# VIM-LIKE BINDINGS FOR READLINE
# We also have the option to run them as scripts with -x,
# but this way the prompt doesn't show up again, it's as if
# the command run "inside" somehow.
# This way we delete anything else and plainly write the 
# command and execute it

# Dynamic branch select
# This messes up greek in arch. not needed for readline commands
#bind 'set convert-meta on'

# Dmenu branches
if type gith &>/dev/null; then
    bind '"\C-h": "\C-e\C-ugith\n"'
fi
# Switch between branches
if type gitk &>/dev/null; then
    bind '"\C-k": "\C-e\C-ugitk\n"'
fi
# Dmenu Projects
if type gitp &>/dev/null; then
    bind '"\C-p": "\C-e\C-ugitp\n"'
fi
if type ranger &>/dev/null; then
    bind '"\M-w": "\C-e\C-uranger\n"'
fi
if type st &>/dev/null; then
    bind '"\M-": "\C-e\C-ust &\n"'
fi
