#!/bin/bash
# Get modified flag
__git_modified() {
	local status=$(git status --porcelain 2> /dev/null)
	if [[ "$status" != "" ]]; then
		echo "*"
	else
		echo ""
	fi
}
# Is running with docker?
running_in_docker() {
  if [ -f /proc/self/cgroup ]; then
      awk -F/ '$2 == "docker"' /proc/self/cgroup | read
  else
      return 1;
  fi
}
_composer_scripts() {
    local cur prev
    _get_comp_words_by_ref -n : cur
 
    COMPREPLY=()
    prev="${COMP_WORDS[COMP_CWORD-1]}"
 
    #
    #  Complete the arguments to some of the commands.
    #
    if [ "$prev" != "composer" ] ; then
        local opts=$(composer $prev -h --no-ansi | tr -cs '[=-=][:alpha:]_' '[\n*]' | grep '^-')
        COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
        return 0
    fi
 
 
    if [[ "$cur" == -* ]]; then
        COMPREPLY=( $( compgen -W '-h -q -v -V -n -d \
            --help --quiet --verbose --version --ansi --no-ansi \
            --no-interaction --profile --working-dir' -- "$cur" ) )
    else
        local scripts=$(composer --no-ansi 2> /dev/null |  awk '/^ +[a-z]+/ { print $1 }')
        COMPREPLY=( $(compgen -W "${scripts}" -- ${cur}) )
    fi
 
    __ltrim_colon_completions "$cur"
    return 0
}
 
