[[ -f ~/.Xresources ]] && xrdb -merge -I$HOME ~/.Xresources

# Set keyboard language
setxkbmap -layout us,gr -option grp:alt_shift_toggle

# Map Caps lock to ESC 
setxkbmap -option caps:escape

# Remap inconvenient "less" key to shift
xmodmap -e "keycode 94 = Shift_L NoSymbol Shift_L"

xbindkeys

eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

owncloud &

exec i3
