# Set keyboard language
setxkbmap -layout us,gr -option grp:alt_shift_toggle

# Map Caps lock to ESC 
setxkbmap -option caps:escape

# Remap inconvenient "less" symbol to shift
xmodmap -e "keycode 94 = Shift_L NoSymbol Shift_L"

xbindkeys

exec i3
